-- Canon DB schema for million-word-novel (Long-Context Narrative Operating System)
-- Canonical DDL. canon_db.py executes this file verbatim; docs/DDL.sql is a copy
-- generated by `python scripts/canon.py ddl` so the documentation can never drift.
--
-- Design rules encoded here:
--   * SQLite + JSON text columns only. No external service, no ORM, no third-party lib.
--   * Markdown (bible.md / plot-ledger.md / summaries) is a DERIVED VIEW, never truth.
--   * Every canon mutation is a row in canon_changes (who/when/what/before/after/why).
--   * Every chapter commit produces exactly one row in snapshots + one JSON delta file.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------- meta
CREATE TABLE IF NOT EXISTS meta (
    key         TEXT PRIMARY KEY,
    value       TEXT
);

-- ---------------------------------------------------------------- chapters
CREATE TABLE IF NOT EXISTS chapters (
    number        INTEGER PRIMARY KEY,
    title         TEXT    NOT NULL DEFAULT '',
    file          TEXT    NOT NULL,
    chars         INTEGER NOT NULL,
    count_mode    TEXT    NOT NULL DEFAULT 'no_ws',
    sha256        TEXT    NOT NULL,
    volume        INTEGER,
    arc           TEXT,
    round_index   INTEGER NOT NULL DEFAULT 0,
    timeline_at   TEXT,
    plan_id       TEXT,
    audit_status  TEXT    NOT NULL DEFAULT 'pending',
    gates         TEXT    NOT NULL DEFAULT '{}',
    commit_id     TEXT    NOT NULL,
    committed_at  TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_chapters_volume  ON chapters(volume);
CREATE INDEX IF NOT EXISTS idx_chapters_round   ON chapters(round_index);

-- ---------------------------------------------------------------- entities
-- kind ∈ character | location | organization | item
CREATE TABLE IF NOT EXISTS entities (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    kind          TEXT NOT NULL,
    name          TEXT NOT NULL,
    aliases       TEXT NOT NULL DEFAULT '[]',
    status        TEXT NOT NULL DEFAULT 'active',
    first_chapter INTEGER,
    last_chapter  INTEGER,
    data          TEXT NOT NULL DEFAULT '{}',
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    UNIQUE (kind, name)
);
CREATE INDEX IF NOT EXISTS idx_entities_kind ON entities(kind);
CREATE INDEX IF NOT EXISTS idx_entities_name ON entities(name);

-- current state of every character (one row per entity, kind='character')
CREATE TABLE IF NOT EXISTS character_states (
    entity_id    INTEGER PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE,
    chapter      INTEGER,
    location     TEXT,
    goal         TEXT,
    emotion      TEXT,
    belief       TEXT NOT NULL DEFAULT '[]',
    knowledge    TEXT NOT NULL DEFAULT '[]',
    health       TEXT,
    possession   TEXT NOT NULL DEFAULT '[]',
    status       TEXT NOT NULL DEFAULT 'alive',
    relationship TEXT NOT NULL DEFAULT '[]',
    updated_at   TEXT
);

-- append-only state change log: BEFORE -> AFTER per field per chapter
CREATE TABLE IF NOT EXISTS character_state_changes (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id    INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    chapter      INTEGER NOT NULL,
    field        TEXT NOT NULL,
    before_value TEXT,
    after_value  TEXT,
    source       TEXT NOT NULL DEFAULT 'canon',
    commit_id    TEXT
);
CREATE INDEX IF NOT EXISTS idx_csc_entity ON character_state_changes(entity_id, chapter);

-- ---------------------------------------------------------------- events
CREATE TABLE IF NOT EXISTS events (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        TEXT UNIQUE,
    chapter     INTEGER NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'event',
    summary     TEXT NOT NULL DEFAULT '',
    participants TEXT NOT NULL DEFAULT '[]',
    location    TEXT,
    timeline_at TEXT,
    causes      TEXT NOT NULL DEFAULT '[]',
    effects     TEXT NOT NULL DEFAULT '[]',
    irreversible INTEGER NOT NULL DEFAULT 0,
    data        TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_events_chapter ON events(chapter);

-- ---------------------------------------------------------------- relationships
CREATE TABLE IF NOT EXISTS relationships (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    from_entity   INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    to_entity     INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'active',
    since_chapter INTEGER,
    until_chapter INTEGER,
    notes         TEXT NOT NULL DEFAULT '',
    UNIQUE (from_entity, to_entity, kind)
);

-- ---------------------------------------------------------------- foreshadowing
-- status ∈ PLANTED | ACTIVE | DEVELOPING | PAYOFF_READY | RESOLVED | STALE_LEAK
CREATE TABLE IF NOT EXISTS foreshadowings (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    code                 TEXT UNIQUE NOT NULL,
    title                TEXT NOT NULL DEFAULT '',
    description          TEXT NOT NULL DEFAULT '',
    status               TEXT NOT NULL DEFAULT 'PLANTED',
    kind                 TEXT NOT NULL DEFAULT 'long',
    planted_chapter      INTEGER,
    planned_payoff_start INTEGER,
    planned_payoff_end   INTEGER,
    resolved_chapter     INTEGER,
    last_touched_chapter INTEGER,
    stages               TEXT NOT NULL DEFAULT '[]',
    leak_detected        INTEGER NOT NULL DEFAULT 0,
    data                 TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_foreshadow_status ON foreshadowings(status);

-- ---------------------------------------------------------------- plot threads
CREATE TABLE IF NOT EXISTS plot_threads (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    code           TEXT UNIQUE NOT NULL,
    name           TEXT NOT NULL,
    kind           TEXT NOT NULL DEFAULT 'sub',
    status         TEXT NOT NULL DEFAULT 'planned',
    opened_chapter INTEGER,
    closed_chapter INTEGER,
    goal           TEXT NOT NULL DEFAULT '',
    arc            TEXT,
    data           TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_thread_status ON plot_threads(status);

-- ---------------------------------------------------------------- world rules
CREATE TABLE IF NOT EXISTS world_rules (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    code          TEXT UNIQUE NOT NULL,
    text          TEXT NOT NULL,
    first_chapter INTEGER,
    immutable     INTEGER NOT NULL DEFAULT 1,
    data          TEXT NOT NULL DEFAULT '{}'
);

-- ---------------------------------------------------------------- knowledge
CREATE TABLE IF NOT EXISTS knowledge (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    knower_id       INTEGER REFERENCES entities(id) ON DELETE CASCADE,
    knower_name     TEXT NOT NULL DEFAULT '',
    fact_code       TEXT NOT NULL,
    fact_text       TEXT NOT NULL DEFAULT '',
    learned_chapter INTEGER,
    source          TEXT NOT NULL DEFAULT '',
    confidence      REAL NOT NULL DEFAULT 1.0,
    secret          INTEGER NOT NULL DEFAULT 0,
    data            TEXT NOT NULL DEFAULT '{}',
    UNIQUE (knower_name, fact_code)
);
CREATE INDEX IF NOT EXISTS idx_knowledge_fact ON knowledge(fact_code);

-- ---------------------------------------------------------------- items
CREATE TABLE IF NOT EXISTS items (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    code      TEXT UNIQUE NOT NULL,
    name      TEXT NOT NULL,
    holder_id INTEGER REFERENCES entities(id) ON DELETE SET NULL,
    location  TEXT,
    state     TEXT NOT NULL DEFAULT '',
    data      TEXT NOT NULL DEFAULT '{}'
);

-- ---------------------------------------------------------------- volumes / arcs
CREATE TABLE IF NOT EXISTS volumes (
    volume              INTEGER PRIMARY KEY,
    start_chapter       INTEGER,
    end_chapter         INTEGER,
    goal                TEXT NOT NULL DEFAULT '',
    irreversible_change TEXT NOT NULL DEFAULT '',
    main_conflict       TEXT NOT NULL DEFAULT '',
    turns               TEXT NOT NULL DEFAULT '',
    hook                TEXT NOT NULL DEFAULT '',
    raw                 TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS arcs (
    code          TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    volume        INTEGER,
    start_chapter INTEGER,
    end_chapter   INTEGER,
    goal          TEXT NOT NULL DEFAULT '',
    status        TEXT NOT NULL DEFAULT 'planned',
    data          TEXT NOT NULL DEFAULT '{}'
);

-- ---------------------------------------------------------------- timeline
CREATE TABLE IF NOT EXISTS timeline (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    chapter     INTEGER NOT NULL UNIQUE,
    world_time  TEXT NOT NULL,
    order_index INTEGER NOT NULL,
    note        TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_timeline_time ON timeline(world_time);

-- ---------------------------------------------------------------- snapshots
CREATE TABLE IF NOT EXISTS snapshots (
    id             TEXT PRIMARY KEY,
    chapter        INTEGER NOT NULL,
    commit_id      TEXT NOT NULL,
    path           TEXT NOT NULL,
    kind           TEXT NOT NULL DEFAULT 'delta',
    base_path      TEXT,
    chapter_sha256 TEXT,
    created_at     TEXT NOT NULL,
    summary        TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_snapshots_chapter ON snapshots(chapter, kind);

-- ---------------------------------------------------------------- plans / audits / gates
CREATE TABLE IF NOT EXISTS plans (
    id          TEXT PRIMARY KEY,
    chapter     INTEGER NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'chapter',
    payload     TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'draft',
    source      TEXT NOT NULL DEFAULT 'rule',
    created_at  TEXT NOT NULL,
    approved_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_plans_chapter ON plans(chapter, kind);

CREATE TABLE IF NOT EXISTS audits (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    chapter      INTEGER NOT NULL,
    level        INTEGER NOT NULL,
    file         TEXT,
    sha256       TEXT,
    pass         INTEGER NOT NULL,
    blocking     TEXT NOT NULL DEFAULT '[]',
    advisories   TEXT NOT NULL DEFAULT '[]',
    provider     TEXT NOT NULL DEFAULT 'rule',
    report_path  TEXT,
    created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audits_chapter ON audits(chapter, sha256);

CREATE TABLE IF NOT EXISTS gates (
    chapter    INTEGER PRIMARY KEY,
    plan       TEXT NOT NULL DEFAULT 'missing',
    audit      TEXT NOT NULL DEFAULT 'missing',
    canon      TEXT NOT NULL DEFAULT 'missing',
    length     TEXT NOT NULL DEFAULT 'missing',
    data       TEXT NOT NULL DEFAULT '{}',
    updated_at TEXT
);

-- ---------------------------------------------------------------- transactions
CREATE TABLE IF NOT EXISTS transactions (
    id           TEXT PRIMARY KEY,
    chapter      INTEGER,
    state        TEXT NOT NULL,
    started_at   TEXT NOT NULL,
    finished_at  TEXT,
    steps        TEXT NOT NULL DEFAULT '[]',
    journal_path TEXT
);
CREATE INDEX IF NOT EXISTS idx_tx_state ON transactions(state);

-- ---------------------------------------------------------------- rounds
CREATE TABLE IF NOT EXISTS round_runs (
    round_index      INTEGER PRIMARY KEY,
    status           TEXT NOT NULL DEFAULT 'open',
    planned_chapters TEXT NOT NULL DEFAULT '[]',
    started_at       TEXT,
    closed_at        TEXT,
    verdict          TEXT,
    blockers         TEXT NOT NULL DEFAULT '[]',
    waivers          TEXT NOT NULL DEFAULT '[]',
    notes            TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS round_tasks (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    round_index INTEGER NOT NULL,
    chapter     INTEGER NOT NULL,
    stage       TEXT NOT NULL DEFAULT 'planned',
    status      TEXT NOT NULL DEFAULT 'pending',
    updated_at  TEXT,
    UNIQUE (round_index, chapter, stage)
);

-- ---------------------------------------------------------------- traceability
CREATE TABLE IF NOT EXISTS canon_changes (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    ts           TEXT NOT NULL,
    actor        TEXT NOT NULL DEFAULT 'system',
    action       TEXT NOT NULL,
    entity_kind  TEXT,
    entity_ref   TEXT,
    field        TEXT,
    before_value TEXT,
    after_value  TEXT,
    reason       TEXT NOT NULL DEFAULT '',
    source       TEXT NOT NULL DEFAULT 'system',
    chapter      INTEGER,
    commit_id    TEXT
);
CREATE INDEX IF NOT EXISTS idx_changes_chapter ON canon_changes(chapter);
CREATE INDEX IF NOT EXISTS idx_changes_entity  ON canon_changes(entity_kind, entity_ref);

CREATE TABLE IF NOT EXISTS warnings (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          TEXT NOT NULL,
    chapter     INTEGER,
    code        TEXT NOT NULL,
    message     TEXT NOT NULL,
    severity    TEXT NOT NULL DEFAULT 'warning',
    entity_kind TEXT,
    entity_ref  TEXT,
    resolved    INTEGER NOT NULL DEFAULT 0,
    data        TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_warnings_chapter ON warnings(chapter);
CREATE INDEX IF NOT EXISTS idx_warnings_code    ON warnings(code);

-- ---------------------------------------------------------------- semantic index
CREATE TABLE IF NOT EXISTS scene_index (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    chapter     INTEGER NOT NULL,
    scene_no    INTEGER NOT NULL,
    location    TEXT,
    participants TEXT NOT NULL DEFAULT '[]',
    conflict    TEXT NOT NULL DEFAULT '',
    summary     TEXT NOT NULL DEFAULT '',
    dialogue_function TEXT NOT NULL DEFAULT '',
    signature   TEXT NOT NULL DEFAULT '',
    UNIQUE (chapter, scene_no)
);
CREATE INDEX IF NOT EXISTS idx_scene_sig ON scene_index(signature);
